apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJkblpzWVdReU1USTZaMmh3WDNCcWJHczFiRGx6VVRsUlZFZ3dSM0ZuUzJOTVNIRnBSbFZOVUhWNk1URmhhMUUwU3c9PSJ9fX0=
type: kubernetes.io/dockerconfigjson
